name: Maven Build and Publish

on:
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate Installation Token
      id: install_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        

        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file Test/pom.xml

    - name: Log in to GitHub Packages
      run: echo "//maven.pkg.github.com/Reny24/TestingJen:TOKEN=${{ steps.install_token.outputs.token }}" >> ~/.m2/settings.xml

    - name: Publish to GitHub Packages
      run: mvn deploy 
