name: Maven Build and Publish

on:
  workflow_dispatch:
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Log in to GitHub Packages
      uses: tibdex/github-app-token@v2
      id: login
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        installation-id: ${{ secrets.INSTALLATION_ID }}

    - name: Publish to GitHub Packages
      run: |
        mvn deploy -Dmaven.test.skip=true -Dregistry=https://maven.pkg.github.com/Reny24/TestingJen -Dtoken=${{ steps.login.outputs.token }}

