name: Publish to GitHub Packages

on:
  workflow_dispatch:
    

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Autenticazione con GitHub App
      - name: Set up GitHub App authentication
        uses: tibdex/github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          installation-id: ${{ secrets.INSTALLATION_ID }}

      # Accesso a GitHub Packages
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build del pacchetto (esempio con Maven)
      - name: Build package
        run: mvn package

      # Pubblicare il pacchetto
      - name: Publish package
        run: mvn deploy
