name: Publish to GitHub Packages

on:
  workflow_dispatch:
    

jobs:
  publish:
    permissions: 
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20   
          

      # Autenticazione con GitHub App
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          
          
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build del pacchetto (esempio con Maven)
      - name: Build package
        run: mvn package

      # Pubblicare il pacchetto
      - name: Publish package
        run: mvn deploy
