name: Publish to GitHub Packages

on:
  workflow_dispatch:
    

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Autenticazione con GitHub App
      - name: Set up GitHub App authentication
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.INSTALLATION_ID }}
          github_api_url: 'https://api.github.com'
          revoke: false
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"

      # Build del pacchetto (esempio con Maven)
      - name: Build package
        run: mvn package

      # Pubblicare il pacchetto
      - name: Publish package
        run: mvn deploy
